var annotated_dup =
[
    [ "SDLib", "namespace_s_d_lib.html", "namespace_s_d_lib" ],
    [ "biosParmBlock", "structbios_parm_block.html", "structbios_parm_block" ],
    [ "BME280_Calibration_Data", "struct_b_m_e280___calibration___data.html", "struct_b_m_e280___calibration___data" ],
    [ "BME280_I2C", "class_b_m_e280___i2_c.html", "class_b_m_e280___i2_c" ],
    [ "cache_t", "unioncache__t.html", "unioncache__t" ],
    [ "CID", "struct_c_i_d.html", "struct_c_i_d" ],
    [ "csd_t", "unioncsd__t.html", "unioncsd__t" ],
    [ "CSDV1", "struct_c_s_d_v1.html", "struct_c_s_d_v1" ],
    [ "CSDV2", "struct_c_s_d_v2.html", "struct_c_s_d_v2" ],
    [ "directoryEntry", "structdirectory_entry.html", "structdirectory_entry" ],
    [ "DS1307RTC", "class_d_s1307_r_t_c.html", "class_d_s1307_r_t_c" ],
    [ "fat32BootSector", "structfat32_boot_sector.html", "structfat32_boot_sector" ],
    [ "LiquidCrystal", "class_liquid_crystal.html", "class_liquid_crystal" ],
    [ "masterBootRecord", "structmaster_boot_record.html", "structmaster_boot_record" ],
    [ "partitionTable", "structpartition_table.html", "structpartition_table" ],
    [ "Sd2Card", "class_sd2_card.html", "class_sd2_card" ],
    [ "SdFile", "class_sd_file.html", "class_sd_file" ],
    [ "SdVolume", "class_sd_volume.html", "class_sd_volume" ],
    [ "spi_options_t", "structspi__options__t.html", "structspi__options__t" ],
    [ "TwoWire", "class_two_wire.html", "class_two_wire" ],
    [ "u_avr32_spi_cr_t", "unionu__avr32__spi__cr__t.html", "unionu__avr32__spi__cr__t" ],
    [ "u_avr32_spi_csr_t", "unionu__avr32__spi__csr__t.html", "unionu__avr32__spi__csr__t" ],
    [ "u_avr32_spi_idr_t", "unionu__avr32__spi__idr__t.html", "unionu__avr32__spi__idr__t" ],
    [ "u_avr32_spi_ier_t", "unionu__avr32__spi__ier__t.html", "unionu__avr32__spi__ier__t" ],
    [ "u_avr32_spi_mr_t", "unionu__avr32__spi__mr__t.html", "unionu__avr32__spi__mr__t" ],
    [ "u_avr32_spi_tdr_t", "unionu__avr32__spi__tdr__t.html", "unionu__avr32__spi__tdr__t" ]
];